In [1]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
X = [[2, 1], [3, 1], [1, 4], [2, 6]]

In [3]:
#定义归一化类的对象
scaler=MinMaxScaler(feature_range=(-1,1))
#应用缩放器
X_scaler=scaler.fit_transform(X)
print(X_scaler)

[[ 0.  -1. ]
 [ 1.  -1. ]
 [-1.   0.2]
 [ 0.   1. ]]


In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
print(X)

[[2, 1], [3, 1], [1, 4], [2, 6]]


In [20]:
#标准化(API)
scaler=StandardScaler()
X_scaler=scaler.fit_transform(X)
print(X_scaler)

[[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]


In [23]:
#标准化计算验证
import numpy as np
X=np.array(X)
print(X)
mean=np.mean(X,axis=0)
std=np.std(X,axis=0)
print("均值：",mean)
print("标准差：",std)
print("标准化结果:\n",(X-mean)/std)

[[2 1]
 [3 1]
 [1 4]
 [2 6]]
均值： [2. 3.]
标准差： [0.70710678 2.12132034]
标准化结果:
 [[ 0.         -0.94280904]
 [ 1.41421356 -0.94280904]
 [-1.41421356  0.47140452]
 [ 0.          1.41421356]]
